# 프로그램 실행 시 테이블 update
spring:
  config:
    activate:
      on-profile: "dev"
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true


# 로깅 설정
logging:
  level:
    org:
      springframework:
        security: trace
        web: DEBUG
      hibernate:
        orm:
          jdbc:
            bind: trace
