#green
version: '3'
services:
  backend:
    build: .
    ports: # 2024/02/28 기존의 8082 -> 80을 임시로 80 -> 8080으로 포워딩하기로 변경
      - "8080:80"
    container_name: sejongpeer-green
    environment:
      - TZ=Asia/Seoul
    env_file:
      - .env
