#blue
version: '3'
services:
  # 서비스의 이름
  backend:
    # 현재 디렉토리에서의 Dockerfile을 사용하여 Docker 이미지를 빌드
    build: .
    # 호스트의 8081 포트와 컨테이너의 80 포트를 매핑
    # 2024/02/28 위 사항을 무시하고  임시로 80 -> 8080으로 포워딩하기로 변경
    ports:
      - "443:80"
    # 컨테이너의 이름
    container_name: sejongpeer-blue
    environment:
      - TZ=Asia/Seoul
    env_file:
      - .env
